Conda
CCPPETMR/SIRF-SuperBuild pull request #112
Opened 2018-04-26 05:41 UTC by paskino

initial working recipe for linux.

OSX would need tweak on build.sh. 

The branch should be aligned with setup_py #109

2018-04-26 08:31 UTC, casperdcl commented
1. merge https://github.com/CCPPETMR/SIRF/pull/160
2. merge #109
3. rebase this and merge

close #106?

2018-04-26 10:58 UTC, paskino commented
I agree with you.

2018-04-27 08:43 UTC, KrisThielemans commented
should we add a conda build to Travis? Maybe it's already done via the docker build.

that'd allow you to test on OSX.

2018-05-08 21:10 UTC, KrisThielemans commented
Data and examples is #102.

2018-05-09 08:54 UTC, evgueni-ovtchinnikov commented
@casperdcl: so far as i can see examples in MR/interactive require simulated_MR_2D_cartesian.h5, which is not in https://github.com/CCPPETMR/SIRF_data/tree/master/examples

@ckolbPTB: why did you not use existing_filepath function? the error message would be more meaningful

also, the graphics in coil_combination.py crashes python when run from command line (spyder survives)

2018-05-12 22:02 UTC, KrisThielemans requested changes
could probably easily split ismrmrd and gadgetron off...

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - nose
`nose` and `coverage` not needed for conda package? (they probably don't make sense)

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - h5py
99% sure we don't need this

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/build.sh
> +echo "$SRC_DIR/ccpi/Python"
really?

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/build.sh
> +# but will currently change your .sirfrc. This is to be avoided later on.
incorrect comment

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/build.sh
> +#fi
until we fix this, will need to add it to the checklist

2018-05-12 22:02 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - openblas
not for build?

2018-05-12 22:45 UTC, paskino commented on conda-recipe/build.sh
> +echo "$SRC_DIR/ccpi/Python"
Really what?

2018-05-12 22:47 UTC, paskino commented on conda-recipe/meta.yaml
> +    - nose
They are needed during the build

2018-05-12 22:48 UTC, KrisThielemans commented on conda-recipe/build.sh
> +echo "$SRC_DIR/ccpi/Python"
ccpi...

2018-05-12 22:49 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - nose
not convinced. they are needed for the testing. but are you testing here?
not a problem to leave them in if it helps of course.

2018-05-12 22:51 UTC, paskino commented
I guess we'll end up creating several recipes which create the packages sirf depends on, and sirf.
As we discussed, we could pass a parameter to the superbuild and build only part of it. Now I don't remember which parameter is exactly.

2018-05-12 22:52 UTC, paskino commented on conda-recipe/meta.yaml
> +    - nose
It wouldn't build otherwise

2018-05-12 22:53 UTC, paskino commented on conda-recipe/build.sh
> +echo "$SRC_DIR/ccpi/Python"
You know, I'm torn

2018-05-12 22:56 UTC, KrisThielemans commented
currently you'd run CMake as usual. then just say `make gadgetron` or whatever. A bit wasteful, but minimal effort...

2018-05-12 22:57 UTC, KrisThielemans commented
this is fine-tuning of course. leave it for later!

2018-05-12 22:58 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - nose
well... in that case, we need it! :-)

2018-05-12 23:41 UTC, casperdcl commented on conda-recipe/meta.yaml
> +    - openblas
I feel like there's a difference between build, install (runtime), and test. I'd think nose and coverage fall into the last category, and things like h5py for install? Is there a way to specify these three categories for conda? I'm sure at least two are possible. At least split into sections with comments

2018-05-13 07:03 UTC, paskino commented on conda-recipe/meta.yaml
> +    - openblas
Indeed there is. Currently The tricky bit is afaik that the install phase of the external packages is run during the make phase.

2018-05-13 07:07 UTC, paskino commented
I wouldn't mind issuing cake 3 or 4 times!

2019-03-02 12:27 UTC, casperdcl commented
> I guess we'll end up creating several recipes which create the packages sirf depends on, and sirf.

helps that STIR is now in `conda-forge`

2019-03-02 13:14 UTC, KrisThielemans commented
> helps that STIR is now in conda-forge

First need to resolve https://github.com/UCL/STIR/issues/211

2019-07-09 21:03 UTC, paskino commented
Directories to pass to `External_SIRF.cmake` are defined 

* For STIR [here](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_STIR.cmake#L128L130)
* NIFTYREG [here](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_NIFTYREG.cmake#L72L74)
* ITK (needed by [STIR](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_STIR.cmake#L109)) where?

2019-11-28 11:24 UTC, KrisThielemans requested changes
I haven't checked this really, but I'm confused about the various `build.sh` files, and then `sirf/build.sh` building other stuff anyway.

2019-11-28 11:24 UTC, KrisThielemans commented on conda/boost/build.sh
> +#!/bin/bash
I would try to avoid building boost at all costs. Use the conda dependency

2019-11-28 11:24 UTC, KrisThielemans commented on conda/hdf5/build.sh
> +#!/bin/bash
let's not build hdf5

2019-11-28 11:24 UTC, KrisThielemans commented on conda/ismrmrd/build.sh
> +    -DSIRF_TAG=v2.1.0\
let's not put explicit versions in any of the conda build.sh. In any case, SIRF version is irrelevant in ismrmrd/build.sh

2019-11-28 11:24 UTC, KrisThielemans commented on conda/sirf/build.sh
> +make -j2 STIR
no need for these.

2019-11-28 11:24 UTC, KrisThielemans commented on conda/stir/build.sh
> +make  -j1 Gadgetron
in stir/build.sh?

2020-05-11 08:07 UTC, KrisThielemans commented
STIR 4.0.1 conda might work ok. There's https://anaconda.org/inati/ismrmrd but it's out-of-date. Might be worth checking with them.

2020-05-11 08:08 UTC, KrisThielemans commented
By the way, I'm not 100% sure what the strategy here was/is, but I think we should have a SIRF-only conda package (with its dependencies, most obtained via conda). I would at least initially not attempt gadgetron-via-conda.

2022-01-05 14:39 UTC, KrisThielemans commented
See https://github.com/gadgetron/gadgetron/pull/1036 for Gadgetron's `conda` efforts

2022-09-02 21:21 UTC, KrisThielemans commented on conda-recipe/meta.yaml
> +    - python 2.7 # [py27]
drop this of course

2026-05-08 12:45 UTC, closed without merging

2026-05-08 12:45 UTC, paskino commented
hugely obsolete work